export enum IMAGE_EXTENSIONS {
  JPG = "jpg",
  JPEG = "jpeg",
  PNG = "png",
  WEBP = "webp",
}

export enum IMAGE_MIME_TYPES {
  JPEG = "image/jpeg",
  PNG = "image/png",
  WEBP = "image/webp",
}

export const ALLOWED_IMAGE_MIME_TYPES: IMAGE_MIME_TYPES[] = [
  IMAGE_MIME_TYPES.JPEG,
  IMAGE_MIME_TYPES.PNG,
  IMAGE_MIME_TYPES.WEBP,
];

export const EXT_TO_MIME: Record<IMAGE_EXTENSIONS, IMAGE_MIME_TYPES> = {
  [IMAGE_EXTENSIONS.JPG]: IMAGE_MIME_TYPES.JPEG,
  [IMAGE_EXTENSIONS.JPEG]: IMAGE_MIME_TYPES.JPEG,
  [IMAGE_EXTENSIONS.PNG]: IMAGE_MIME_TYPES.PNG,
  [IMAGE_EXTENSIONS.WEBP]: IMAGE_MIME_TYPES.WEBP,
};

export const MIME_TO_EXT: Record<IMAGE_MIME_TYPES, IMAGE_EXTENSIONS> = {
  [IMAGE_MIME_TYPES.JPEG]: IMAGE_EXTENSIONS.JPG,
  [IMAGE_MIME_TYPES.PNG]: IMAGE_EXTENSIONS.PNG,
  [IMAGE_MIME_TYPES.WEBP]: IMAGE_EXTENSIONS.WEBP,
};

export const MAX_IMAGE_FILE_SIZE_MB = 7;

export const MAX_IMAGE_FILE_SIZE_BYTES = 7 * 1024 * 1024;

export const MAX_IMAGES_PER_USER = 50;

export const IMAGE_OPTIMIZE_MAX_WIDTH = 800;

export const IMAGE_OPTIMIZE_MAX_HEIGHT = 800;

export const IMAGE_OPTIMIZE_QUALITY = 0.75;
