export type RoomType =
  | "seminar (ios)"
  | "seminar (android)"
  | "seminar (web)"
  | "seminar (lounge)"
  | "lobby"
  | "mogakco"
  | "restaurant"
  | "desk zone"
  | "meeting (web 1-10)"
  | "meeting (web 11-20)"
  | "meeting (web 21-30)"
  | "meeting (ios 1-5)"
  | "meeting (android 1-3)"
  | "meeting (web 1)"
  | "meeting (web 2)"
  | "meeting (web 3)"
  | "meeting (web 4)"
  | "meeting (web 5)"
  | "meeting (web 6)"
  | "meeting (web 7)"
  | "meeting (web 8)"
  | "meeting (web 9)"
  | "meeting (web 10)"
  | "meeting (web 11)"
  | "meeting (web 12)"
  | "meeting (web 13)"
  | "meeting (web 14)"
  | "meeting (web 15)"
  | "meeting (web 16)"
  | "meeting (web 17)"
  | "meeting (web 18)"
  | "meeting (web 19)"
  | "meeting (web 20)"
  | "meeting (web 21)"
  | "meeting (web 22)"
  | "meeting (web 23)"
  | "meeting (web 24)"
  | "meeting (web 25)"
  | "meeting (web 26)"
  | "meeting (web 27)"
  | "meeting (web 28)"
  | "meeting (web 29)"
  | "meeting (web 30)"
  | "meeting (ios 1)"
  | "meeting (ios 2)"
  | "meeting (ios 3)"
  | "meeting (ios 4)"
  | "meeting (ios 5)"
  | "meeting (android 1)"
  | "meeting (android 2)"
  | "meeting (android 3)";
